HairSalon/Models/Client.cs
namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string ClientName { get; set; }
    public int StylistId { get; set; }
    public Stylist Stylist { get; set; }
  }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
      public DbSet<Stylist> Stylists { get; set; }
      public DbSet<Client> Clients { get; set; }
      public HairSalonContext(DbContextOptions options) : base(options) { }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    public string StylistName { get; set; }
    public int StylistId { get; set; }
    public List<Client> Clients { get; set; }
  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;
    
    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }
        
    public ActionResult Index()
  
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }
  }
}

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to Eau Claire's Salon</h1>
<p>@Html.ActionLink("See all available stylists", "Index", "Stylists")

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <!-- <title>@ViewBag.PageTitle</title> -->
    <title>Eau Claire's Salon</title>
    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
      crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;

<h1>Available Stylists</h1>

@if (@Model.Count == 0)
{
  <h3>No Stylists in database. Please add at least one stylist to begin assigning clients.</h3>
}

<ul>
  @foreach(Stylist stylist in Model)
  {
    <li>@Html.ActionLink($"{stylist.StylistName}", "Details", new { id = stylist.StylistId })</li>
  }
  </ul>

  <p>@Html.ActionLink("Add a new stylist", "Create", "Stylists")</p